### PR TITLE
Now we check the freshness of cache based on nextupdate tag in meta

### LINKED ISSUE #26: Keep a cache valid as long as the meta data suggests
The meta group in the XML file has the following information

```
<meta>
        <lastupdate>2015-04-20T12:53:00</lastupdate>
        <nextupdate>2015-04-21T01:30:00</nextupdate>
</meta>
```
It is clear that no new weather data will be available till the `<nextupdate>` hence doing API calls will not yield any new information.

We should use the information in <nextupdate> to expire the cache instead of a 15 minutes timeout :)

### PR DESCRIPTION
**Pull request by knightsamar**
Fixes #26

### CODE REVIEW

**Comment by idxxx23** [comment]
Good Job!

I see that you use Python 2.7, if you want you can manage python2 branch.

pm


Dne 20.4.2015 v 18:15 Samarendra M Hedaoo napsal(a):

**Comment by knightsamar** [comment]
Thanks! 

Sure I can do that. I have a python 2.7 compatible version of your project (https://github.com/knightsamar/python-yr-2/) I don't remember the merge compatibility of that fork and python2 branch  at this repo since it's a long time I did that. Also, I don't remember exactly what were the problems that I couldn't use the python2 branch. But I can maintain the branch for sure :+1:

**Comment by idxxx23** [comment]
I sent Alex info, that you'll primary care for python2 branch. I assume the rights will be to the whole project ... does not make sense to set restrictions ... welcome on a board ;)

**Comment by knightsamar** [comment]
Thanks :+1: :)

**Pull request merged**
